name: 'Checkout Repository Standard'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history.'
    required: false
    default: '1'

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}